### ISSUE TITLE
Composer require doctrine/dbal - Not possible

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/fusio#136] opened 2018-03-31 17:29 UTC
I tried to install ```doctrine/dbal``` in a fresh fusio installation (only ```composer create-project fusio/fusio``` was run so far)

Command:
```bash
composer require doctrine/dbal
```
Result:
```bash
Using version ^2.6 for doctrine/dbal
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - psx/sql v2.1.1 requires doctrine/dbal ~2.5.0 -> satisfiable by doctrine/dbal[2.5.x-dev, v2.5.0, v2.5.0-BETA2, v2.5.0-BETA3, v2.5.0-RC1, v2.5.0-RC2, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9] but these conflict with your requirements or minimum-stability.
    - psx/sql v2.1.1 requires doctrine/dbal ~2.5.0 -> satisfiable by doctrine/dbal[2.5.x-dev, v2.5.0, v2.5.0-BETA2, v2.5.0-BETA3, v2.5.0-RC1, v2.5.0-RC2, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9] but these conflict with your requirements or minimum-stability.
    - psx/sql v2.1.1 requires doctrine/dbal ~2.5.0 -> satisfiable by doctrine/dbal[2.5.x-dev, v2.5.0, v2.5.0-BETA2, v2.5.0-BETA3, v2.5.0-RC1, v2.5.0-RC2, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9] but these conflict with your requirements or minimum-stability.
    - Installation request for psx/sql (locked at v2.1.1) -> satisfiable by psx/sql[v2.1.1].

Installation failed, reverting ./composer.json to its original content.
```

I'm not sure, why composer isn't satisfied by v2.5.* (should be stable?) and I guess it's not directly a fusio problem, but maybe you can help to identify the real issue?

Just to be clear:
I know that doctrine/dbal is already installed by psx/sql, but IMHO it's not a bad practice to rely on that (e.g. psx/sql could change the db layer).

**Possible workaround - explicitly require doctrine/dbal 2.5.*:**
```bash
composer require doctrine/dbal:"^2.5"
```

**Comment by k42b3** [comment] 2018-03-31 21:49
Hi, yes we are currently requiring doctrine/dbal v2.5 since the v2.6 had an issue with the sqlite driver and because of this the tests were not working correctly. But I will check whether the problem is resolved by now, in this case we could upgrade to v2.6

**Comment by chriskapp** [comment] 2019-08-30 19:04
In the next 1.8 release we will finally update doctrine/dbal to 2.9 which should also fix this issue.

**Closed by chriskapp** 2019-08-30 19:04 UTC
Labels: question
