### ISSUE TITLE
Endpoint sends image/png

### ISSUE THREAD

**Issue by twenster** [apioo/fusio#212] opened 2019-01-30 11:45 UTC
Hi,

I have an endpoint sending a PNG image (content-type image/png). A direct call send a correct stream. However through fusio, the stream seems corrupted and is stopped.
I thought my end point wasn't getting the right parameters from Fusio, but the returned header show a correct filename (which contains my parameters).

I don't see why the stream is stopped or considered as malformed...

Log received by Insomnia for a direct call to the endpoint:
```
< HTTP/1.1 200 OK
< Date: Wed, 30 Jan 2019 11:25:58 GMT
< Server: Apache
< Content-Disposition: inline; filename="image-Ni-CeNa-Ce.png"
< Strict-Transport-Security: max-age=16000000; includeSubDomains; preload
< Upgrade: h2
< Connection: Upgrade
< Transfer-Encoding: chunked
< Content-Type: image/png

* Received 6 B chunk
* Received 7.6 KB chunk
* Received 2 B chunk
* Received 6 B chunk
* Received 7.6 KB chunk
* Received 2 B chunk
* Received 6 B chunk
* Received 7.6 KB chunk
* Received 2 B chunk
* Received 6 B chunk
* Received 7.6 KB chunk
* Received 2 B chunk
* Received 6 B chunk
* Received 7.6 KB chunk
* Received 2 B chunk
* Received 6 B chunk
* Received 7.6 KB chunk
* Received 2 B chunk
* Received 6 B chunk
* Received 7.6 KB chunk
* Received 2 B chunk
* Received 6 B chunk
* Received 7.6 KB chunk
* Received 2 B chunk
* Received 6 B chunk
* Received 7.6 KB chunk
* Received 2 B chunk
* Received 6 B chunk
* Received 7.6 KB chunk
* Received 2 B chunk
* Received 647 B chunk
* Received 5 B chunk
* Connection #81 to host mydomain.com left intact
```

Log received from Insomnia for a call through Fusio:

```
< HTTP/1.1 200 OK
< Date: Wed, 30 Jan 2019 11:38:43 GMT
< Server: Apache
< content-disposition: inline; filename="image-Ni-CeNa-Ce.png"
< strict-transport-security: max-age=16000000; includeSubDomains; preload
< upgrade: h2
< connection: Upgrade
< transfer-encoding: chunked
< Upgrade: h2
< Connection: Upgrade
< Content-Type: image/png

* Received 7.6 KB chunk
* Malformed encoding found in chunked-encoding
* stopped the pause stream!
* Closing connection 86
* TLSv1.2 (OUT), TLS alert, Client hello (1):
```

**Comment by chriskapp** [comment] 2019-01-30 20:01
Hi, ok it looks like the issue is related to #208 in the way that Fusio handels not correctly chunked encoding. Could you open the file `vendor/psx/http/src/Server/Sender.php` and change line 113-117 from:

```
if ($transferEncoding == 'chunked') {
	$this->sendContentChunked($response);
} else {
	$this->sendContentEncoded($contentEncoding, $response);
}
```

simply to:

```
$this->sendContentEncoded($contentEncoding, $response);
```

This basically disables the chunked encoding handling. Iam also thinking about removing this feature in the next release since it makes some problems. Could you check whether this fixes your problem.

**Comment by twenster** [comment] 2019-02-01 10:51
I also feared the problem was linked to #208 ;)
I played a bit around my code and your edit. Here is what I come up for now.

- When the endpoint sends an image with a known length, Content-Transfer is not chunked, and Fusio handles nicely the stream. (your edits have no influence)

- When the endpoint sends an image without a known length (no Content-length in the header), Apache switches to chunked transfers (normal behaviour). Without the edit, the stream is broken. With your edit, the stream is also broken as Apache advertise a chunked stream, but Fusio sends the whole image at once (not chunked).

So I have either to find out how to get the size of an PHP created image, or how to disable chunked transfer in Apache on my shared hosting... Or if you have another suggestion :)

**Comment by chriskapp** [comment] 2019-02-03 17:48
Ok in the end iam planing to remove the chunked encoding logic inside Fusio, since HTTP/2 doesnt support chunked transfer encoding and for the future it has no real benefits. Also even if Fusio contains no chunked encoding logic the Apache can still send the response chunked. But regarding your problem, you could probably use something like: http://php.net/manual/de/function.getimagesize.php
to get the image size and then set manually the content length header.

**Comment by twenster** [comment] 2019-02-03 17:57
I tried already getimagesize(). That's why I notice my second problem. The image is created by PHP, and doesn't exist anywhere on the drive. getimagesize() can apparently only check the size of an existing file, not an in-memory image :-/

Thanks however for the hint :)

**Comment by chriskapp** [comment] 2019-02-10 19:07
Hi, ok so FYI the latest release contains now the updated sender php class without the chunked encoding so you may want to test this new release. Regarding the `getimagesize` I think in general it is not needed to set this header since the Apache can automatically decide either to use a `Content-Length` header or send the data chunked encoded.

**Comment by twenster** [comment] 2019-03-06 19:46
Hi ! I installed the version 1.5.1. Now requesting the route from a browser work fine ! I get the right answer (JSON) from an route, and the PNG image from another. Fantastic!

Funny thing though, from Insomnia, those links are not working anymore...

Instead of getting the JSON, get
```
< HTTP/1.1 400 Bad Request
< Date: Wed, 06 Mar 2019 19:38:02 GMT
< Server: Apache
< vary: accept-language,accept-charset
< strict-transport-security: max-age=16000000; includeSubDomains; preload
< upgrade: h2
< connection: Upgrade, close
< accept-ranges: bytes
< content-language: en
< Upgrade: h2
< Connection: Upgrade
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=utf-8

* Received 932 B chunk
* Received 5 B chunk
* Closing connection 17
* TLSv1.2 (OUT), TLS alert, Client hello (1):

```

And instead of the PNG, I get:
```
< HTTP/1.1 200 OK
< Date: Wed, 06 Mar 2019 19:31:46 GMT
< Server: Apache
< content-disposition: inline; filename="AtOMo-Ni-CeNa-Ce.png"
< strict-transport-security: max-age=16000000; includeSubDomains; preload
< upgrade: h2
< connection: Upgrade
< transfer-encoding: chunked
< Upgrade: h2
< Connection: Upgrade
< Content-Type: image/png

* Received 7.6 KB chunk
* Illegal or missing hexadecimal sequence in chunked-encoding
* stopped the pause stream!
* Closing connection 15
* TLSv1.2 (OUT), TLS alert, Client hello (1):
```

**Comment by chriskapp** [comment] 2019-09-01 06:28
I will close this issue, since I think it is resolved

**Closed by chriskapp** 2019-09-01 06:28 UTC
Labels: question
