### ISSUE TITLE
PHP extension "cassandra" is not installed in/var/www/html/fusio/vendor/fusio/adapter-cassandra/src/Connection/Cassandra.php on line 75

### ISSUE THREAD

**Issue by 273735889** [apioo/fusio#250] opened 2019-08-08 07:04 UTC
I used docker-deployed fusio, and now I need to install Fusio-Adapter-Cassandra, which I installed under the container.

The first step is to run composer require fusio/adapter-cassandra with the output of:

Use version ^ 0.5.0 for fusio/adapter-cassandra

/ composer.json has been updated

Loading composer repositories with package information

Updating dependencies (including require-dev)

Package operations: 2 installs, 0 updates, 0 removals

- Installing datastax/php-driver (v1.3.1): Download (100%)

- Installing fusio/adapter-cassandra (v0.5.0): Download (100%)

Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

Writing lock file

Generating autoload files

Ocramius/package-versions: Generating version class...

Ocramius / package-versions:... Do generate version class

The second step is to run PHP bin/fusio system: register ""Fusio Adapter Cassandra Adapter"at www/html/fusio, and the output is

The adapter will install the following entries into the system.

+ ----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+

| Type | Description|

+ ----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+

| Connection Class | Fusio Adapter Cassandra Connection Cassandra|

+ ----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+

Do you want to continue (y/n)?

Registration successful!

The third step is to login to fusio. When creating a connection, you can see the option of cassandra, but when I configure it to click save, it appears.

PHP extension "cassandra" is not installed in/var/www/html/fusio/vendor/fusio/adapter-cassandra/src/Connection/Cassandra.php on line 75

Could you help me see it, thank you.

**Comment by chriskapp** [comment] 2019-08-08 18:59
Hi, sure, so basically you have done everything right. You only need to install the PHP extension "cassandra" which is needed so that PHP can talk to a cassandra database. Please take a look at: https://docs.datastax.com/en/developer/php-driver/1.3/building/ to see how to install the driver.

**Comment by 273735889** [comment] 2019-08-09 02:44
I'm glad to receive your reply. At present, the image version of fuiso is latest. I see that the current version of PHP is 7.2, while the compatible version of https://docs.datastax.com/en/developer/php-driver/1.3/building/does not support it. There are other better ways to reduce the image version to below v1.50. Are you looking forward to your reply?

**Comment by 273735889** [comment] 2019-08-09 03:00
I am very excited to receive your reply. The image I am using at present is fuiso/fusio: latest. I noticed that the PHP version in the container is 7.2, while the compatible version of https://docs.datastax.com/en/developer/php-driver/1.3/building/do does does not support 7.2. Is there a better way to reduce the image version of Fusio to v1.0.0? I look forward to your reply. Thank you.

**Comment by 273735889** [comment] 2019-08-09 03:04
I am very excited to receive your reply. At present, I use image fuiso/fusio: latest. I noticed that the PHP version in the container is 7.2. In the connection https://docs.datastax.com/en/developer/php-driver/1.3/building/I found that it does not support PHP 7.2. Is there a better way to reduce the image version of Fusio to v1.0.0? Looking forward to your reply, Thank you

**Comment by chriskapp** [comment] 2019-08-10 13:03
mhh ok I think the problem is that the PHP driver of Cassandra is not actively maintained anymore and therefor only a version for PHP 7.1 is available, maybe you can ask about 7.2 support in there user mailinglist: https://groups.google.com/a/lists.datastax.com/forum/#!forum/php-driver-user

Otherwise you could change the PHP version of the docker container to 7.1. This should then work also with the extension.

**Comment by 273735889** [comment] 2019-08-13 03:08
hi , chriskapp,
Fusio's web interface configuration cassandra, did not find the place to enter user name and password,  is it not supported by itself?
Looking forward to your reply, Thank you

**Comment by 273735889** [comment] 2019-08-13 05:48
hi,chriskapp,I recompiled an extension to support php7.2, and then I changed fusio-adapter-cassandra/src/Connection/Cassandra.php to allow it to receive usernames and passwords. At present, I can successfully create a connection. I'll go on to the next step. Thank you for your help.

**Comment by chriskapp** [comment] 2019-08-13 18:07
Ok, great, please let me know if there are any further issues.

**Comment by 273735889** [comment] 2019-08-14 02:18
ok,nice,Thank you for your help. Welcome to Changsha, China.




------------------ 原始邮件 ------------------
发件人: "Christoph Kappestein"<notifications@github.com>; 
发送时间: 2019年8月14日(星期三) 凌晨2:07
收件人: "apioo/fusio"<fusio@noreply.github.com>; 
抄送: "伊梦依香"<273735889@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [apioo/fusio] PHP extension "cassandra" is not installedin/var/www/html/fusio/vendor/fusio/adapter-cassandra/src/Connection/Cassandra.phpon line 75 (#250)




Ok, great, please let me know if there are any further issues.

**Comment by chriskapp** [comment] 2019-08-14 17:45
I just noticed, if you like you might want to commit those username/password changes upstream to the adapter at: https://github.com/apioo/fusio-adapter-cassandra

**Comment by chriskapp** [comment] 2019-09-01 06:05
So thanks for the PR, I will close this issue since it is resolved.

**Closed by chriskapp** 2019-09-01 06:05 UTC
Labels: question
