### ISSUE TITLE
Deploy fusio.yml error

### ISSUE THREAD

**Issue by flyinggman** [apioo/fusio#39] opened 2017-05-23 21:49 UTC
Hi,

When trying to run the deploy command (php bin/fusio deploy), I get the following error:
- [ERROR] connection Default-Connection: An exception occured in driver: could not find driver
- [UPDATED] schema Todo
- [UPDATED] schema Todo-Collection
- [UPDATED] schema Todo-Message
- [UPDATED] action TodoRow
- [UPDATED] action TodoDelete
- [UPDATED] action TodoCollection
- [UPDATED] action TodoInsert
- [UPDATED] routes /todo/:todo_id
- [UPDATED] routes /todo
- [ERROR] Default-Connection resources/sql/v1_schema.sql: Could not found connection Default-Connection

I have fusio 0.4.0 installed.

Support would be appreciated.

**Comment by k42b3** [comment] 2017-05-23 22:14
Hi, mhh this looks like you dont have the PHP sqlite extension installed. The demo API uses by default a sqlite connection, but you can also simply change this to a mysql connection in the `.fusio.yml` file. If you have fixed the connection you can simply run the deploy command `php bin/fusio deploy` again, which then should create the fitting table on the connection.

**Comment by flyinggman** [comment] 2017-05-24 11:42
Worked like a charm- thanks for the fast and effective response.

**Comment by flyinggman** [comment] 2017-05-24 13:06
Apologies for opening the issue again. I got the message "deployed successful!" now, however the back-end (routes etc) is still empty.

**Comment by k42b3** [comment] 2017-05-24 16:26
You are welcome. Regarding the ticket, I think we should close the issue #38 in favor of this one. Normally I would suspect that the route table contains now the `/todo` endpoints. Could you maybe make a fresh installation and try to reproduce the error. I would assume that this is some sort of an upgrade error. Or can you take a look at the database and see whether a `routes` entry is actually available in the `fusio_routes` table.

**Comment by flyinggman** [comment] 2017-05-24 18:57
Tables (including fusio_routes) seem to be fine with entries populated. But back-end doesnt seem to pick anything up from the database (apart from username/password which I believe are accessed otherwise I wouldnt be able to login in the first place).

**Comment by k42b3** [comment] 2017-05-27 13:36
Mhh could you take a look at the developer console in your browser to see what is the exact http response of the `/backend/routes` request. Is there a json response with no entry or an error response?

**Comment by flyinggman** [comment] 2017-05-30 07:05
There is an error 401 Unaithorized

**Comment by k42b3** [comment] 2017-06-14 16:27
If you get a `Missing authorization header` response your session is maybe expired. It is also possible that `mod_rewrite` is not correctly configured and thus the `Authorization` header is not passed correctly to Fusio. Please take a look at the [documentation](http://fusio.readthedocs.io/en/latest/installation.html#backend). Otherwise do you have additional debuging information so that I can reproduce your error?

**Comment by k42b3** [comment] 2017-06-28 19:18
I will close this error, if you have any further issues please create a new or reopen this issue.

**Closed by k42b3** 2017-06-28 19:18 UTC
Labels: bug
