### ISSUE TITLE
I think is a fu***** Server Error. HELP!!

### ISSUE THREAD

**Issue by bezael** [apioo/fusio#60] opened 2017-09-04 18:45 UTC
This is my HTTPD Config, but on the route always show me this: No input file specified.

What's do you think is it??

Thanks

<VirtualHost 0.0.0.0:80>

    ServerName midominio.com
    ServerAlias www.midominio.com
    ServerAdmin info@midominio.com
    DocumentRoot /home/user/web/midominio.com/public_html/fusio/public/
    ScriptAlias /cgi-bin/ /home/user/web/midominio.com/cgi-bin/
    Alias /vstats/ /home/user/web/midominio.com/stats/
    Alias /error/ /home/user/web/midominio.com/document_errors/
    SuexecUserGroup user user
    CustomLog /var/log/httpd/domains/midominio.com.bytes bytes
    CustomLog /var/log/httpd/domains/midominio.com.log combined
    ErrorLog /var/log/httpd/domains/midominio.com.error.log
    <Directory /home/user/web/midominio.com/public_html/fusio>
        AllowOverride All
        Options +Includes -Indexes +ExecCGI -MultiViews
        php_admin_value open_basedir /home/user/web/midominio.com/public_html/fusio:/home/user/tmp
        php_admin_value upload_tmp_dir /home/user/tmp
        php_admin_value session.save_path /home/user/tmp
        <Files *.php>
          SetHandler fcgid-script
        </Files>
        FCGIWrapper /home/user/web/midominio.com/cgi-bin/fcgi-starter .php
    </Directory>
    <Directory /home/user/web/midominio.com/stats>
        AllowOverride All
    </Directory>
    IncludeOptional /home/user/conf/web/httpd.midominio.com.conf*

</VirtualHost>

**Comment by k42b3** [comment] 2017-09-04 18:54
Hi, please relax ;), emotions dont solve problems. It looks like the error "No input file specified" is related to the webserver and not Fusio directly, you could check SO:
https://stackoverflow.com/questions/14555996/no-input-file-specified

Otherwise please set the `psx_debug` setting to true and call the route endpoint. This should give you details about the error message.

**Comment by bezael** [comment] 2017-09-04 19:03
im sorry dud, im really crazy with that.  :(

Thanks thats solved!

**Comment by k42b3** [comment] 2017-09-05 06:31
Ok, so I close this error since the problem is solved.

**Closed by k42b3** 2017-09-05 06:31 UTC
