### ISSUE TITLE
Route's scope disappear misteriously

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#72] opened 2017-10-14 09:20 UTC
Incidentally I can not access a certain end point of my API. I can access it before. 
It said that I am not authorized to access this end point. I am sure I have set the correct scope.

Coincidentally, this end point does not shown up in update scope popup due to #67 issue.
So I checked the database. I found out that no entry exist for this route.

I do not know how to reproduce it. I will post it here if I found out a way to reproduce it.
It happen several times. Unfortunately, I do not record any information about it.

**Comment by k42b3** [comment] 2017-10-14 10:21
Ok, I can only imagine, if you use the deploy mechanism all scopes are removed and then added for each route. Maybe this step has somehow removed the scope. But please let me know if you can reproduce this error.

**Comment by zaniar** [comment] 2017-10-16 09:01
It happens again. I practically doing nothing. I just accessing the API via my app & using the backend normally.

**Comment by zaniar** [comment] 2017-10-16 09:16
Ok. I got it. It is related to https://github.com/apioo/fusio/issues/67#issuecomment-336111287.
After I click save, the whole entries of fusio_scope_routes deleted, and filled with new entries.

**Comment by zaniar** [comment] 2017-10-16 09:19
if https://github.com/apioo/fusio/issues/67#issuecomment-336111287 can be solved, I think this issue will be solved too.

But, I still feel it is weird that the save operation wipe out the entire old data. Should be only update the changed values.

**Comment by k42b3** [comment] 2017-10-16 19:29
Ok, now I can understand the problem. At the moment we [delete all route assignments](https://github.com/apioo/fusio-impl/blob/master/src/Service/Scope.php#L176) to the scope and then add the new selected routes from the request, this also all done in a transaction. We do this to simply avoid calculating the diff which scopes were updated/removed.

**Comment by k42b3** [comment] 2017-11-03 00:01
I think we can close this issue since #67 is solved. Regarding the delete handling we leave this for now since the code is tested and we are in the "release candidate" stage where we dont want to introduce new big changes.

**Closed by k42b3** 2017-11-03 00:01 UTC
Labels: bug
