### ISSUE TITLE
Deployment Problem

### ISSUE THREAD

**Issue by subangkit** [apioo/fusio#45] opened 2017-07-18 00:18 UTC
Hello, 

I receive error message Could not resolve action App-HelloWorld-Action-Collection at vendor/fusio/impl/src/Service/System/SystemAbstract.php(110): Fusio\Impl\Service\System\SystemAbstract->transformRoutes(Object(stdClass))

I've setting configuration with engine to PHPClass, and set .fusio.yml.

**Comment by k42b3** [comment] 2017-07-18 06:35
Hi, if you set the engine to `PHPClass` the class which you define at the action must be autoloadable through composer. In your case I assume that you must have created a class at `src/HelloWorld/Action/Collection.php`. Could you also show me your `.fusio.yml` config so I can better debug your problem.

**Comment by subangkit** [comment] 2017-07-18 09:32
This is my .fusio.yml

`routes:
  "/currency":
    version: 1
    methods:
      GET:
        public: true
        response: HelloWorld-Collection
        action: App\HelloWorld\Action\Collection
      POST:
        public: false
        response: Message
        request: HelloWorld
        action: App\HelloWorld\Action\Insert
  "/currency/:currency_code":
    version: 1
    methods:
      GET:
        public: true
        response: HelloWorld
        action: App\HelloWorld\Action\Row
      POST:
        public: false
        response: Message
        request: HelloWorld
        action: App\HelloWorld\Action\Update
      DELETE:
        public: false
        response: Message
        action: App\HelloWorld\Action\Delete
schema:
  HelloWorld: !include resources/schema/helloworld/entity.json
  HelloWorld-Collection: !include resources/schema/helloworld/collection.json
  Message: !include resources/schema/default/message.json
connection:
  Default-Connection:
    class: Fusio\Adapter\Sql\Connection\Sql
    config:
      type: pdo_mysql
      host: localhost
      username: root
      password: root
      database: data_helloworld
migration:
  Default-Connection:
    - resources/sql/v1_akun_schema.sql`

**Comment by k42b3** [comment] 2017-07-18 19:05
Ok thanks, as far as I can see the `.fusio.yml` config looks good. Could you show me the content of your class file at `src/HelloWorld/Action/Collection.php`. This file should contain the collection class. To update the composer autoload file you could run `composer dump-autoload`. Do you have installed the current version of Fusio?

**Comment by subangkit** [comment] 2017-07-19 04:42
This is Collection Class, and has modified with Dev Extreme Library to provide OData Schema.
But the point is why `App\HelloWorld\Action` cant find by fusio even I has run `composer dump-autoload` command. Yes I've use current version. I just clone from github 2 days ago.

`<?php

namespace App\HelloWorld\Action;

require_once(__DIR__."/../../../vendor/devextreme/LoadHelper.php");
spl_autoload_register(array("DevExtreme\LoadHelper", "LoadModule"));

use Fusio\Engine\ActionAbstract;
use Fusio\Engine\ContextInterface;
use Fusio\Engine\ParametersInterface;
use Fusio\Engine\RequestInterface;
use DevExtreme\DbSet;
use DevExtreme\DataSourceLoader;
use Doctrine\DBAL\Driver\Mysqli\MysqliConnection;

class Collection extends ActionAbstract
{
    private $dbSet;

    function _json_decode($str) {
        if(is_string($str)) {
            if (json_decode($str,true) != NULL) {
                $str = json_decode($str,true);
                return $this->_json_decode($str);
            }
            return $str;
        } else if (is_array($str)) {
            foreach ($str as $index => $value) {
                $str[$index] = $this->_json_decode($value);
            }
            return $str;
        }
    }

    public function handle(RequestInterface $request, ParametersInterface $configuration, ContextInterface $context)
    {
        $connection = $this->connector->getConnection('Default-Connection');
        $connectionParams = $connection->getParams();
        $mySQL = new MysqliConnection(['dbname' => $connectionParams['dbname'], 'host' => $connectionParams['host']], $connectionParams['user'], $connectionParams['password']);
        $this->dbSet = new DbSet($mySQL->getWrappedResourceHandle(), "helloworld");
        $param = $_GET;

        $param['requireTotalCount'] = true;
        if (isset($param['skip']))
            $param['skip'] = (int) $param['skip'];

        if (isset($param['take']))
        $param['take'] = (int) $param['take'];

        if (isset($param['filter'])) {
            $param['filter'] = $this->_json_decode($param['filter']);
        }


        if (isset($param['sort'])){
            $sortArray = json_decode($param['sort'],true);
            if (isset($sortArray['selector']))
                $param['sort'] = [json_decode($param['sort'])];
            else {
                $param['sort'] = $sortArray;
            }
        }

        if (isset($param['group'])){
            $sortArray = json_decode($param['group'],true);
            if (isset($sortArray['selector']))
                $param['group'] = [json_decode($param['group'])];
            else {
                $param['group'] = $sortArray;
            }
        }

        $result = DataSourceLoader::Load($this->dbSet, $param);
        if (!isset($result)) {
            $result = $this->dbSet->GetLastError();
        }
        return $this->response->build(200, [], $result);
    }
}
`

**Comment by k42b3** [comment] 2017-07-19 16:43
Ok, can you use the action without the `spl_autoload_register` call? Maybe this autoloader is the reason why Fusio is not able to load the class. Everything else looks ok.

* As improvement you could try to use in your `.fusio.yml` at the  `Default-Connection` the `type: mysqli`. Then you should get directly a `MysqliConnection`. In this way you open up only one connection per request.
* Also it is probably better to use `$request->getParameters()` insteadof `$_GET` so that your action does not depend on a global state.

**Comment by subangkit** [comment] 2017-07-20 09:07
I try to remove `spl_autoload_register` but still getting same error. So I try to copy from previous version of fusio 0.9.0 then copy same resource and same Action from current version fusio. All my code is working good. Maybe between 0.9.0 to current version of fusio has some update that make auto-load not working.

Thank you for suggestion, that make better code with fusio, and I hope as soon as seen production version.

**Comment by k42b3** [comment] 2017-07-20 16:44
Mhh in the 0.9.0 release we have introduced the engine parameter which tells Fusio how to interpret an action, so this could be indeed a problem. After you have updated the files of Fusio did you run the `bin/fusio install` script again? Through this Fusio can update the internal database schema etc. Also could you show me the content of your `fusio_action` table?

**Comment by k42b3** [comment] 2017-07-29 20:28
Hi, do you have still problems regarding this issue otherwise I would like to close it since ot looks like it is a problem with the autoloading and not directly an issue of Fusio

**Comment by subangkit** [comment] 2017-08-01 00:47
Hi., I still facing the problem. And in my case is freshly install of current version of fusio.

**Comment by k42b3** [comment] 2017-08-01 06:12
Ok, could you tell me the steps so that I can reproduce the problem on a fresh installation. Otherwise it is difficult for me to find a solution since Iam not sure what the concrete problem is.

**Comment by subangkit** [comment] 2017-08-02 21:26
1. `git clone https://github.com/apioo/fusio.git`
2. Create fusio database and change `configuration.php`
3. `> php bin/fusio install`
4. Modify .fusio.yml
`routes:
  "/helloworld":
    version: 1
    methods:
      GET:
        public: true
        response: HelloWorld-Collection
        action: App\HelloWorld\Action\Collection
      POST:
        public: false
        response: Message
        request: HelloWorld
        action: App\HelloWorld\Action\Insert
  "/helloworld/:helloworld_code":
    version: 1
    methods:
      GET:
        public: true
        response: HelloWorld
        action: App\HelloWorld\Action\Row
      POST:
        public: false
        response: Message
        request: HelloWorld
        action: App\HelloWorld\Action\Update
      DELETE:
        public: false
        response: Message
        action: App\HelloWorld\Action\Delete
schema:
  HelloWorld: !include resources/schema/helloworld/entity.json
  HelloWorld-Collection: !include resources/schema/helloworld/collection.json
  Message: !include resources/schema/default/message.json
connection:
  Default-Connection:
    class: Fusio\Adapter\Sql\Connection\Sql
    config:
      type: pdo_mysql
      host: localhost
      username: root
      password: root
      database: data_helloworld
migration:
  Default-Connection:
    - resources/sql/v1_akun_schema.sql`
5. Create entity.json and collection.json 
resource/schema/helloworld/entity.json
`{
  "type": "object",
  "title": "hello",
  "properties": {
    "code": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
  },
  "required": [
    "name",
  ]
}`
resource/schema/helloworld/collection.json
`{
  "type": "object",
  "title": "hello-collection",
  "properties": {
    "totalCount": {
      "type": "integer"
    },
    "data": {
      "type": "array",
      "items": {
        "$ref": "file:///entity.json"
      }
    }
  }
}`
6. Create Action File in `src/HelloWorld/Action/Collection.php`
`
namespace App\HelloWorld\Action;

require_once(__DIR__."/../../../vendor/devextreme/LoadHelper.php");
spl_autoload_register(array("DevExtreme\LoadHelper", "LoadModule"));

use Fusio\Engine\ActionAbstract;
use Fusio\Engine\ContextInterface;
use Fusio\Engine\ParametersInterface;
use Fusio\Engine\RequestInterface;
use DevExtreme\DbSet;
use DevExtreme\DataSourceLoader;
use Doctrine\DBAL\Driver\Mysqli\MysqliConnection;

class Collection extends ActionAbstract
{
    private $dbSet;

    function _json_decode($str) {
        if(is_string($str)) {
            if (json_decode($str,true) != NULL) {
                $str = json_decode($str,true);
                return $this->_json_decode($str);
            }
            return $str;
        } else if (is_array($str)) {
            foreach ($str as $index => $value) {
                $str[$index] = $this->_json_decode($value);
            }
            return $str;
        }
    }

    public function handle(RequestInterface $request, ParametersInterface $configuration, ContextInterface $context)
    {
        $connection = $this->connector->getConnection('Default-Connection');
        $connectionParams = $connection->getParams();
        $mySQL = new MysqliConnection(['dbname' => $connectionParams['dbname'], 'host' => $connectionParams['host']], $connectionParams['user'], $connectionParams['password']);
        $this->dbSet = new DbSet($mySQL->getWrappedResourceHandle(), "helloworld");
        $param = $_GET;

        $param['requireTotalCount'] = true;
        if (isset($param['skip']))
            $param['skip'] = (int) $param['skip'];

        if (isset($param['take']))
        $param['take'] = (int) $param['take'];

        if (isset($param['filter'])) {
            $param['filter'] = $this->_json_decode($param['filter']);
        }


        if (isset($param['sort'])){
            $sortArray = json_decode($param['sort'],true);
            if (isset($sortArray['selector']))
                $param['sort'] = [json_decode($param['sort'])];
            else {
                $param['sort'] = $sortArray;
            }
        }

        if (isset($param['group'])){
            $sortArray = json_decode($param['group'],true);
            if (isset($sortArray['selector']))
                $param['group'] = [json_decode($param['group'])];
            else {
                $param['group'] = $sortArray;
            }
        }

        $result = DataSourceLoader::Load($this->dbSet, $param);
        if (!isset($result)) {
            $result = $this->dbSet->GetLastError();
        }
        return $this->response->build(200, [], $result);
    }
}
`
7. then, `> php bin/fusio deploy`

**Comment by k42b3** [comment] 2017-08-03 16:58
Ok, thanks I will try to reproduce the issue

**Comment by k42b3** [comment] 2017-08-03 17:33
Ok, so in the end I could make it work. Your last error `Could not resolve action App-HelloWorld-Action-Collection` exists due to a wrong setting on the `configuration.php`. There you need to change the following configuration:
`'fusio_engine' => \Fusio\Engine\Factory\Resolver\PhpClass::class,`

Since you are using the DevExtreme library it would be great if the author would also add this library to packagist so that it would be possible to install it through composer. So you might want to open an issue at the DevExtreme project regarding this.

**Comment by subangkit** [comment] 2017-08-05 14:06
Wow., I using `\Fusio\Impl\Factory\Resolver\PhpFile::class,`. Can you tell me what different between `\Fusio\Impl\Factory\Resolver\PhpFile::class,` and `\Fusio\Engine\Factory\Resolver\PhpClass::class`. because I follow instruction from fusio 0.9.0 which using PhpClass then after 0.9.2 the instruction become using `\Fusio\Impl\Factory\Resolver\JavascriptFile::class`.  Maybe this is suggestion to create more detail documentation and example for this project. 

Thank you for testing bro. I just create fusio 0.9.0 for production purpose even it not ready yet. But it really help me to saving my time.

Regards,

**Closed** 2017-08-05 14:08 UTC
Labels: bug
