### ISSUE TITLE
Feature: Login timeout reset by any activity by user

### ISSUE THREAD

**Issue by EvoPulseGaming** [apioo/fusio#264] opened 2019-09-29 04:53 UTC
Right now, either via the backend, or via REST services, after a set amount of time, the user is logged out due to a hardcoded timeout value. It would be nice if user activity would reset this timer so they don't get kicked out of a session and possibly loose work

**Comment by chriskapp** [comment] 2019-09-29 06:36
The problem is currently the token which you obtain has an expire time. I think the best solution would be to check at the frontend whether the token is about to expire and then exchange this token for a new one. Also if we would implement #245 this would be really helpful since then we could use the OAuth2 refresh token system.

**Comment by ratsey** [comment] 2019-12-18 00:26
> check at the frontend whether the token is about to expire and then exchange this token for a new one

@chriskapp Are you suggesting that this can be done now, or that it's your proposed solution for implementation in a future version?

I have basic authentication working just fine, but have the same issue that @EvoPulseGaming talks about. I started looking at the OAuth2 implementation but, to be honest, it looks like huge overkill for what I need when all I really need is a refreshable token.

**Comment by chriskapp** [comment] 2019-12-18 08:45
@ratsey so this is not solved currently since you dont yet obtain a refresh token if you use the `/consumer/login` endpoint. But I have just commited some changes for the next release which help you with that. So if you use the `/consumer/login` endpoint it will also return a refresh token and you can send a `PUT` request to the `/consumer/login` endpoint including the refresh token which gives you a new access token. In your frontend you would then need to periodically extend the token. This is basically a more simpler version if you dont want to use OAuth2. It is also possible to change the expire date of the token at the `configuration.php` file there you can change the setting `fusio_expire_consumer`

**Comment by ratsey** [comment] 2020-01-27 19:39
Doing my best to be patient :-) ... do you have any plans for the next release that will include this option?

**Comment by chriskapp** [comment] 2020-02-05 19:15
We have just released the new 1.9 version which includes this option therefore I will close this issue.

**Closed by chriskapp** 2020-02-05 19:15 UTC
Labels: feature

**Comment by EvoPulseGaming** [comment] 2020-02-06 02:03
OMG! I'll check it out.
