### ISSUE TITLE
My installation works fine except developer portal

### ISSUE THREAD

**Issue by harshalone** [apioo/fusio#234] opened 2019-06-27 09:00 UTC
My installation works fine except developer portal

I have installed Fusio on my shared hosting with softaculous

Everything works fine except my developer portal looks like this
https://api.bebluebox.com/public/developer/

I am guessing its related to some path issue. how can I fix it?

**Comment by chriskapp** [comment] 2019-07-01 20:15
Hi, sure so the problem is that you need to set the correct `<base href="...">` path at the `public/developer/index.html` file, then it should work as expected.

**Comment by chriskapp** [comment] 2019-09-01 06:25
I think we can close this issue, in the next release we have also the new marketplace which solves this problem by automatically creating the fitting base path for the app.

**Closed by chriskapp** 2019-09-01 06:25 UTC
Labels: question
