### ISSUE TITLE
I want to implement redis cache on auth tokens, is that possible?

### ISSUE THREAD

**Issue by anas-gaditek** [apioo/fusio#333] opened 2020-10-01 15:24 UTC

**Comment by chriskapp** [comment] 2020-10-01 19:05
Hi, mhhh no this is currently not possible since all tokens are stored at the database, what would be the use case to store the token at the redis cache?

**Comment by anas-gaditek** [comment] 2020-10-08 16:13
Hello, Actually I want to store the tokens at redis cache and serve them as well.

**Comment by chriskapp** [comment] 2021-02-14 18:53
So this is not possible since Fusio needs the token at the database to make specific queries. I will close this issue since it looks like the problem is solved.

**Closed by chriskapp** 2021-02-14 18:53 UTC
Labels: question
